Repository timwangmusic/Vacation-Planner, pull requests merged in 2020-12, with the labels that each got.

#158 modify Dockerfile to fix go build issue
  Dockerfile
  build_steps.sh
Labels: Ready To Review

#157 Add request id in get plans API context
  config/config.yml
  go.mod
  go.sum
  iowrappers/data_migrations.go
  iowrappers/nearby_search.go
  iowrappers/poi_searcher.go
  iowrappers/redis_client.go
  planner/planner_API.go
Labels: enhancement

#148 Add sign-up and login pages
  iowrappers/maps_client.go
  planner/planner_API.go
  templates/index.html
  templates/login_page.html
  templates/plan_layout.html
  templates/signup_page.html
Labels: Feature Development
