Repository timwangmusic/Vacation-Planner, pull requests merged in 2023-09, with the labels that each got.

#311 Fix: add user_ratings_total to details search fields list
  config/config.yml
Labels: bug

#309 Allow one place to appear multiple times in the search result page
  config/config.yml
  planner/solver.go
Labels: Feature Development, Ready To Review

#312 Update Place freshness logic
  iowrappers/nearby_search.go
  iowrappers/poi_searcher.go
  iowrappers/redis_client.go
  test/redis_client_mocks/maps_last_search_time_test.go
Labels: enhancement

#314 Enhance: nearby search logging
  iowrappers/nearby_search.go
  matching/time.go
  planner/solver.go
Labels: enhancement

#307 Feat: Search with nearby cities
  assets/js/search.js
  config/config.yml
  go.mod
  go.sum
  iowrappers/photos_client.go
  iowrappers/poi_searcher.go
  iowrappers/redis_client.go
  main.go
  planner/MDIter.go
  planner/planner.go
  planner/planner_test.go
  planner/solver.go
  planner/transformers.go
  planner/utils.go
  templates/search_page.html
  test/solution_candidate_selection_test.go
Labels: Feature Development

#319 Experiement: use a new formula for places price level zero
  matching/score.go
  test/score_test.go
Labels: enhancement

#317 Add a filter to remove places with zero user rating count
  iowrappers/poi_searcher.go
  iowrappers/redis_client.go
  iowrappers/utils.go
  matching/matcher.go
  planner/solver.go
Labels: Ready To Review
