Repository timwangmusic/Vacation-Planner, pull requests merged in 2023-08, with the labels that each got.

#299 Chore: upgrade Go version to 1.21
  .github/workflows/go.yml
  go.mod
  iowrappers/data_migrations.go
  utils/math.go
Labels: go

#301 Fix: discard erroneous city retrieval results from Redis
  iowrappers/redis_client.go
  test/redis_client_mocks/nearby_cities_search_test.go
Labels: bug

#303 Fix: nearby city search in Redis should consider city population
  go.mod
  go.sum
  iowrappers/poi_searcher.go
  iowrappers/redis_client.go
  iowrappers/transformers.go
  test/redis_client_mocks/nearby_cities_search_test.go
Labels: bug

#302 [Feature] Implement a new travel plan persistence index
  POI/places.go
  POI/time_intervals.go
  iowrappers/redis_client.go
  planner/solver.go
  planner/transformers.go
  test/redis_client_mocks/cached_planning_solutions_test.go
Labels: Feature Development

#306 Generics: make min priority queue generic
  planner/min_priority_queue.go
  planner/min_priority_queue_vertex_test.go
  planner/solver.go
  planner/vertex.go
Labels: refactor

#270 [Enhancements]Deduplicate travel plans by place
  planner/solver.go
Labels: enhancement, Ready To Review
